{{- if .Values.chihuahua_node.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: chihuahua-node-1
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 1317
      name: chihuahuad-api
    - port: 9090
      name: chihuahuad-grpc
    - port: 26656
      name: chihuahuad-p2p
    - port: 26657
      name: chihuahuad-rpc
  selector:
    chihuahua.network/node: "1"
{{- end }}